### ISSUE TITLE
Error while doing "yarn start"

### ISSUE THREAD

**Issue by esteblock** [soroswap/interface#7]
```
yarn run v1.22.19
$ craco start
fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse HEAD
fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.<anonymous> (/workspace/craco.config.cjs:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at module.exports (/workspace/node_modules/import-fresh/index.js:32:59) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(164) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32, 100, 101, 116, 101,  99,
      116, 101, 100,  32, 100, 117,  98, 105, 111, 117, 115,  32,
      111, 119, 110, 101, 114, 115, 104, 105, 112,  32, 105, 110,
       32, 114, 101, 112, 111, 115, 105, 116, 111, 114, 121,  32,
       97, 116,  32,  39,  47, 119, 111, 114, 107, 115, 112,  97,
       99, 101,  39,  10,  84, 111,  32,  97, 100, 100,  32,  97,
      110,  32, 101, 120,  99, 101, 112, 116, 105, 111, 110,  32,
      102, 111, 114,  32, 116, 104, 105, 115,  32, 100, 105, 114,
      101,  99, 116, 111,
      ... 64 more items
    ]
  ],
  pid: 701,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(164) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32, 100, 101, 116, 101,  99,
    116, 101, 100,  32, 100, 117,  98, 105, 111, 117, 115,  32,
    111, 119, 110, 101, 114, 115, 104, 105, 112,  32, 105, 110,
     32, 114, 101, 112, 111, 115, 105, 116, 111, 114, 121,  32,
     97, 116,  32,  39,  47, 119, 111, 114, 107, 115, 112,  97,
     99, 101,  39,  10,  84, 111,  32,  97, 100, 100,  32,  97,
    110,  32, 101, 120,  99, 101, 112, 116, 105, 111, 110,  32,
    102, 111, 114,  32, 116, 104, 105, 115,  32, 100, 105, 114,
    101,  99, 116, 111,
    ... 64 more items
  ]
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by chopan123** [comment]
Done on commit [28c5d1dd7bdc55f59498514b3b07a67acf52dd68](https://github.com/Uniswap/interface/commit/28c5d1dd7bdc55f59498514b3b07a67acf52dd68)
